### ISSUE TITLE
IOError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by HongweiLuan** [yardstick17/image_text_reader#1]
When I followed the example but used my own picture, I got this error. My error report is as follows
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in read_image_from_file
  File "<stdin>", line 7, in extract_image_text
  File "<stdin>", line 3, in read_contours_text
  File "<stdin>", line 10, in get_text_with_location
  File "<stdin>", line 7, in extract_image_from_location
  File "C:\ProgramData\Anaconda2\lib\site-packages\PIL\Image.py", line 2410, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 13] Permission denied: 'c:\\users\\hongwei\\appdata\\local\\temp\\tmphyfwny.jpg'

**Comment by yardstick17** [comment]
Hey @HongweiLuan 
You can refer this StackOverflow link: [IOError: [Errno 13] Permission denied in python](https://stackoverflow.com/questions/40254488/ioerror-errno-13-permission-denied-in-python)

I believe the error is because you don't have the root access to write at the given path. Also, you can either run with admin access or you can change the path where the image is being written.
