### ISSUE TITLE
Error after run

### ISSUE THREAD

**Issue by arvitaly** [yardstick17/image_text_reader#2]
Hi!
> docker run -it yardstick17/image-text-reader bash -c 'PYTHONPATH='.' python3 read_image.py read_text_from_local_image -f 2.jpg'

> python3: -c: line 0: unexpected EOF while looking for matching `''
> python3: -c: line 1: syntax error: unexpected end of file

What the problem?

**Comment by yardstick17** [comment]
`docker run -it yardstick17/image-text-reader bash -c "PYTHONPATH='.' python3 read_image.py read_text_from_local_image -f images/sample_image.jpg" 
`- Fixed it in the `README.md`

**Comment by arvitaly** [comment]
```
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Consult http://click.pocoo.org/python3/for mitigation steps.

This system supports the C.UTF-8 locale which is recommended.
You might be able to resolve your issue by exporting the
following environment variables:

    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8
```

Ok, i added 

>  -e LC_ALL=C.UTF-8 -e LANG=C.UTF-8


Now, new error (file 2.jpg exists in folder, where i run `docker run`):

```
[2018-06-23 00:21:19,212] INFO : Processing image for text Extraction
Traceback (most recent call last):
  File "read_image.py", line 124, in <module>
    cli()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "read_image.py", line 109, in read_text_from_local_image
    return read_image_from_file(filename)
  File "read_image.py", line 81, in read_image_from_file
    image = process_image_for_ocr(filename)
  File "/home/image_preprocessing/remove_noise.py", line 27, in process_image_for_ocr
    temp_filename = set_image_dpi(file_path)
  File "/home/image_preprocessing/remove_noise.py", line 33, in set_image_dpi
    im = Image.open(file_path)
  File "/usr/local/lib/python3.5/dist-packages/PIL/Image.py", line 2312, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './2.jpg'
```

**Comment by yardstick17** [comment]
Hey @arvitaly 
```bash
docker run -it -e LC_ALL=C.UTF-8 -e LANG=C.UTF-8 yardstick17/image-text-reader bash -c "PYTHONPATH='.' python3 read_image.py read_text_from_local_image -f images/sample_image.jpg"
```
I ran this on my local machine, it worked fine.  Maybe it is the different locale requirement needed. Please have a look here.

https://stackoverflow.com/a/54903423/4572274
