### ISSUE TITLE
Error while testing

### ISSUE THREAD

**Issue by pranavrajt** [yardstick17/image_text_reader#3]
Hey, I am new to OCR and was trying I was just trying to this locally using the commands you had provided. I am getting the following error. 

[2019-02-26 15:41:04,244] INFO : Downloading image from url: https://marketplace.canva.com/MACHUlPU93Q/1/0/thumbnail_large/canva-peach-green-leaves-garden-vegeta
[2019-02-26 15:41:04,395] INFO : Saving file: /var/folders/wd/p0271j0x695_t5m5h0zr0dd00000gp/T/tmpzj06kyq7
[2019-02-26 15:41:04,395] INFO : Processing image for text Extraction
[2019-02-26 15:41:04,527] INFO : Removing noise and smoothening image
Traceback (most recent call last):
  File "read_image.py", line 135, in <module>
    cli()
  File "/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "read_image.py", line 127, in read_text_from_image_url
    return read_image_from_file(filename)
  File "read_image.py", line 92, in read_image_from_file
    image_text = extract_image_text(image)
  File "read_image.py", line 36, in extract_image_text
    contours = find_possible_contours_in_image(inv_img)
  File "read_image.py", line 85, in find_possible_contours_in_image
    dilated, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)  # get contours
ValueError: not enough values to unpack (expected 3, got 2)

Can you tell me where i am going wrong with this

**Comment by yardstick17** [comment]
@pranavrajt Can you try again, maybe it was because the opencv version was not pinned. I would suggest to install the requirements again and try the command to see if this works for you.

Commit to fix the issue: https://github.com/yardstick17/image_text_reader/commit/6c0199ff005b8e21c45634604b3e11e1da6a7884

**Comment by Salinatorimperator** [comment]
Same issue here, after `pip install -r requirements.txt` works.
